version = 1
SPDX-PackageName = "tutorial-actions"
SPDX-PackageSupplier = "Dmytro Ivanov (dmyturo.ivanov01@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-tutorials/tutorial-actions"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and https://github.com/sap-tutorials/tutorial-actions contributors"
SPDX-License-Identifier = "CC-BY-4.0"
